### ISSUE TITLE
Fails to build with FFmpeg 5.0

### ISSUE THREAD

**Issue by paddatrapper** [savonet/ocaml-ffmpeg#54]
ocaml-ffmpeg currently fails to build with ffmpeg 5.0 due to `/<<PKGBUILDDIR>>/_build/default/avutil/avutil_stubs.c:1277: undefined reference to 'av_opt_child_class_next'`:

```
ocaml-ffmpeg FTBFS with ffmpeg 5.0 (available in experimental):
| x86_64-linux-gnu-gcc avdevice/avdevice_stubs.o
| In file included from avdevice_stubs.c:5:
| avdevice_stubs.c: In function ‘ocaml_avdevice_get_audio_input_formats’:
| avdevice_stubs.c:49:32: warning: passing argument 1 of ‘get_input_devices’ from incompatible pointer type [-Wincompatible-pointer-types]
|    49 |   CAMLreturn(get_input_devices(av_input_audio_device_next));
|       |                                ^~~~~~~~~~~~~~~~~~~~~~~~~~
|       |                                |
|       |                                const AVInputFormat * (*)(const AVInputFormat *)
| /usr/lib/ocaml/caml/memory.h:460:29: note: in definition of macro ‘CAMLreturnT’
|   460 |   type caml__temp_result = (result); \
|       |                             ^~~~~~
| avdevice_stubs.c:49:3: note: in expansion of macro ‘CAMLreturn’
|    49 |   CAMLreturn(get_input_devices(av_input_audio_device_next));
|       |   ^~~~~~~~~~
| avdevice_stubs.c:23:36: note: expected ‘AVInputFormat * (*)(AVInputFormat *)’ but argument is of type ‘const AVInputFormat * (*)(const AVInputFormat *)’
|    23 | get_input_devices(AVInputFormat *(*input_device_next)(AVInputFormat *)) {
|       |                   ~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
| In file included from avdevice_stubs.c:5:
| avdevice_stubs.c: In function ‘ocaml_avdevice_get_video_input_formats’:
| avdevice_stubs.c:54:32: warning: passing argument 1 of ‘get_input_devices’ from incompatible pointer type [-Wincompatible-pointer-types]
|    54 |   CAMLreturn(get_input_devices(av_input_video_device_next));
|       |                                ^~~~~~~~~~~~~~~~~~~~~~~~~~
|       |                                |
|       |                                const AVInputFormat * (*)(const AVInputFormat *)
| /usr/lib/ocaml/caml/memory.h:460:29: note: in definition of macro ‘CAMLreturnT’
|   460 |   type caml__temp_result = (result); \
|       |                             ^~~~~~
| avdevice_stubs.c:54:3: note: in expansion of macro ‘CAMLreturn’
|    54 |   CAMLreturn(get_input_devices(av_input_video_device_next));
|       |   ^~~~~~~~~~
| avdevice_stubs.c:23:36: note: expected ‘AVInputFormat * (*)(AVInputFormat *)’ but argument is of type ‘const AVInputFormat * (*)(const AVInputFormat *)’
|    23 | get_input_devices(AVInputFormat *(*input_device_next)(AVInputFormat *)) {
|       |                   ~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
| In file included from avdevice_stubs.c:5:
| avdevice_stubs.c: In function ‘ocaml_avdevice_get_audio_output_formats’:
| avdevice_stubs.c:83:33: warning: passing argument 1 of ‘get_output_devices’ from incompatible pointer type [-Wincompatible-pointer-types]
|    83 |   CAMLreturn(get_output_devices(av_output_audio_device_next));
|       |                                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~
|       |                                 |
|       |                                 const AVOutputFormat * (*)(const AVOutputFormat *)
| /usr/lib/ocaml/caml/memory.h:460:29: note: in definition of macro ‘CAMLreturnT’
|   460 |   type caml__temp_result = (result); \
|       |                             ^~~~~~
| avdevice_stubs.c:83:3: note: in expansion of macro ‘CAMLreturn’
|    83 |   CAMLreturn(get_output_devices(av_output_audio_device_next));
|       |   ^~~~~~~~~~
| avdevice_stubs.c:58:38: note: expected ‘AVOutputFormat * (*)(AVOutputFormat *)’ but argument is of type ‘const AVOutputFormat * (*)(const AVOutputFormat *)’
|    58 | get_output_devices(AVOutputFormat *(*output_device_next)(AVOutputFormat *)) {
|       |                    ~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
| In file included from avdevice_stubs.c:5:
| avdevice_stubs.c: In function ‘ocaml_avdevice_get_video_output_formats’:
| avdevice_stubs.c:88:33: warning: passing argument 1 of ‘get_output_devices’ from incompatible pointer type [-Wincompatible-pointer-types]
|    88 |   CAMLreturn(get_output_devices(av_output_video_device_next));
|       |                                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~
|       |                                 |
|       |                                 const AVOutputFormat * (*)(const AVOutputFormat *)
| /usr/lib/ocaml/caml/memory.h:460:29: note: in definition of macro ‘CAMLreturnT’
|   460 |   type caml__temp_result = (result); \
|       |                             ^~~~~~
| avdevice_stubs.c:88:3: note: in expansion of macro ‘CAMLreturn’
|    88 |   CAMLreturn(get_output_devices(av_output_video_device_next));
|       |   ^~~~~~~~~~
| avdevice_stubs.c:58:38: note: expected ‘AVOutputFormat * (*)(AVOutputFormat *)’ but argument is of type ‘const AVOutputFormat * (*)(const AVOutputFormat *)’
|    58 | get_output_devices(AVOutputFormat *(*output_device_next)(AVOutputFormat *)) {
|       |                    ~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
| x86_64-linux-gnu-gcc avfilter/avfilter_stubs.o
| avfilter_stubs.c: In function ‘ocaml_avfilter_get_all_filters’:
| avfilter_stubs.c:101:5: warning: ‘avfilter_pad_count’ is deprecated [-Wdeprecated-declarations]
|   101 |     Store_field(cur, 2,
|       |     ^~~~~~~~~~~
| In file included from avfilter_stubs.c:12:
| /usr/include/x86_64-linux-gnu/libavfilter/avfilter.h:80:5: note: declared here
|    80 | int avfilter_pad_count(const AVFilterPad *pads);
|       |     ^~~~~~~~~~~~~~~~~~
| avfilter_stubs.c:104:5: warning: ‘avfilter_pad_count’ is deprecated [-Wdeprecated-declarations]
|   104 |     Store_field(cur, 3,
|       |     ^~~~~~~~~~~
| In file included from avfilter_stubs.c:12:
| /usr/include/x86_64-linux-gnu/libavfilter/avfilter.h:80:5: note: declared here
|    80 | int avfilter_pad_count(const AVFilterPad *pads);
|       |     ^~~~~~~~~~~~~~~~~~
| x86_64-linux-gnu-gcc avutil/avutil_stubs.o
| avutil_stubs.c: In function ‘ocaml_avutil_av_opt_next’:
| avutil_stubs.c:1277:11: warning: implicit declaration of function ‘av_opt_child_class_next’; did you mean ‘av_opt_child_class_iterate’? [-Wimplicit-function-declaration]
|  1277 |           av_opt_child_class_next((const AVClass *)_class, _class_cursor);
|       |           ^~~~~~~~~~~~~~~~~~~~~~~
|       |           av_opt_child_class_iterate
| avutil_stubs.c:1276:21: warning: assignment to ‘const AVClass *’ from ‘int’ makes pointer from integer without a cast [-Wint-conversion]
|  1276 |       _class_cursor =
|       |                     ^
| x86_64-linux-gnu-gcc avcodec/avcodec_stubs.o
| avcodec_stubs.c: In function ‘find_encoder_by_name’:
| avcodec_stubs.c:892:20: warning: initialization discards ‘const’ qualifier from pointer target type [-Wdiscarded-qualifiers]
|   892 |   AVCodec *codec = avcodec_find_encoder_by_name(name);
|       |                    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
| avcodec_stubs.c: In function ‘find_encoder’:
| avcodec_stubs.c:903:20: warning: initialization discards ‘const’ qualifier from pointer target type [-Wdiscarded-qualifiers]
|   903 |   AVCodec *codec = avcodec_find_encoder(id);
|       |                    ^~~~~~~~~~~~~~~~~~~~
| avcodec_stubs.c: In function ‘find_decoder_by_name’:
| avcodec_stubs.c:914:20: warning: initialization discards ‘const’ qualifier from pointer target type [-Wdiscarded-qualifiers]
|   914 |   AVCodec *codec = avcodec_find_decoder_by_name(name);
|       |                    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
| avcodec_stubs.c: In function ‘find_decoder’:
| avcodec_stubs.c:925:20: warning: initialization discards ‘const’ qualifier from pointer target type [-Wdiscarded-qualifiers]
|   925 |   AVCodec *codec = avcodec_find_decoder(id);
|       |                    ^~~~~~~~~~~~~~~~~~~~
| x86_64-linux-gnu-gcc av/av_stubs.o
| av_stubs.c: In function ‘ocaml_av_find_input_format’:
| av_stubs.c:558:27: warning: initialization discards ‘const’ qualifier from pointer target type [-Wdiscarded-qualifiers]
|   558 |   AVInputFormat *format = av_find_input_format(short_name);
|       |                           ^~~~~~~~~~~~~~~~~~~~
| av_stubs.c: In function ‘open_stream_index’:
| av_stubs.c:896:9: warning: assignment discards ‘const’ qualifier from pointer target type [-Wdiscarded-qualifiers]
|   896 |     dec = avcodec_find_decoder(dec_param->codec_id);
|       |         ^
| av_stubs.c: In function ‘ocaml_av_output_format_guess’:
| av_stubs.c:1290:11: warning: assignment discards ‘const’ qualifier from pointer target type [-Wdiscarded-qualifiers]
|  1290 |   guessed = av_guess_format(short_name, filename, mime);
|       |           ^
|     ocamlopt examples/all_codecs.exe (exit 2)
| (cd _build/default && /usr/bin/ocamlopt.opt -w @1..3@5..28@30..39@43@46..47@49..57@61..62-40 -strict-sequence -strict-formats -short-paths -keep-locs -warn-error -A -g -o examples/all_codecs.exe /usr/lib/ocaml/unix.cmxa -I /usr/lib/ocaml /usr/lib/ocaml/threads/threads.cmxa -I /usr/lib/ocaml avutil/avutil.cmxa -I avutil avcodec/avcodec.cmxa -I avcodec examples/.all_codecs.eobjs/native/dune__exe__All_codecs.cmx)
| /usr/bin/ld: avutil/libavutil_stubs.a(avutil_stubs.o): in function `ocaml_avutil_av_opt_next':
| /<<PKGBUILDDIR>>/_build/default/avutil/avutil_stubs.c:1277: undefined reference to `av_opt_child_class_next'
| collect2: error: ld returned 1 exit status
```

Full bug report: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1004573

**Comment by smimram** [comment]
FWIW, it's compiling here, but with the following related warning:
```
avutil_stubs.c: In function ‘ocaml_avutil_av_opt_next’:
avutil_stubs.c:1277:11: warning: ‘av_opt_child_class_next’ is deprecated [-Wdeprecated-declarations]
 1277 |           av_opt_child_class_next((const AVClass *)_class, _class_cursor);
      |           ^~~~~~~~~~~~~~~~~~~~~~~
In file included from avutil_stubs.c:16:
/usr/include/x86_64-linux-gnu/libavutil/opt.h:661:16: note: declared here
  661 | const AVClass *av_opt_child_class_next(const AVClass *parent, const AVClass *prev);
      |                ^~~~~~~~~~~~~~~~~~~~~~~
```

**Comment by toots** [comment]
Sorry closed to soon. Will keep this open and close it when we do the next release, probably soon.

**Comment by toots** [comment]
This is fixed with the release of `v1.1.2`.

**Comment by paddatrapper** [comment]
Thanks! I'll get that packaged shortly
